### ISSUE TITLE
Base64 Library - Decode() support?

### ISSUE THREAD

**Issue by twominutecode** [OpenZeppelin/solidity-jwt#3]
Include the Base64 Decode function in the library contract.

**Comment by frangio** [comment]
This repository is an experiment and the Base64 library is included only for its available functionality, not offered as a feature.

See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2859

**Comment by twominutecode** [comment]
I just wanted a base64 decoder in solidity. Is that possible?
